version: "3.8"

services:
  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
      - 80:80
    links:
      - postgres
      - pgadmin
      - server
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nvnapp.ga
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
      SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  server:
    build: .
    container_name: "walleto-server"
    ports:
      - ${PORT}:${PORT}
      - ${QUEUE_HTTP_PORT}:${QUEUE_HTTP_PORT}
    volumes:
      - .:/app/server
      - ./.logs:/app/server/.logs
    links:
      - redis

  redis:
    image: redis
    container_name: "walleto-redis"
    environment:
      REDIS_QUEUE_PORT: ${REDIS_QUEUE_PORT}
    command: ["redis-server", "--bind", "redis", "--port", "$REDIS_QUEUE_PORT"]
    ports:
      - "${REDIS_QUEUE_PORT}:${REDIS_QUEUE_PORT}"

volumes:
  postgres-data:
  pgadmin-data:
