version: "3.8"

networks:
  walleto:
    name: "walleto-network"
    external: true

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    container_name: "walleto-server"
    networks:
      - walleto
    volumes:
      - ./.logs:/home/node/app/.logs
